networks:
  esdb-net:
    name: esdb-net
    driver: bridge

volumes:
  esdb0-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume/ex-esdb/data0
  esdb1-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume/ex-esdb/data1
  esdb2-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume/ex-esdb/data2
  esdb3-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume/ex-esdb/data3
  esdb4-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume/ex-esdb/data4

services:
  ex-esdb0:
    image: local/ex-esdb
    build:
      context: ../system
    hostname: node0
    container_name: ex-esdb0
    volumes:
      - esdb0-data:/data
    networks:
      - esdb-net
    environment:
      EX_ESDB_STORE_ID: "reg_gh"
      EX_ESDB_COOKIE: "reg_gh_clique1"
      EX_ESDB_SEED_NODES: "ex_esdb@node0"
  #   healthcheck:
  #     test: ["CMD-SHELL", "./check-ex-esdb.sh"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 30s
  #
  ex-esdb1:
    image: local/ex-esdb
    build:
      context: ../system
    hostname: node1
    container_name: ex-esdb1
    volumes:
      - esdb1-data:/data
    networks:
      - esdb-net
    environment:
      EX_ESDB_STORE_ID: "reg_gh"
      EX_ESDB_COOKIE: "reg_gh_clique1"
      EX_ESDB_SEED_NODES: "ex_esdb@node0,ex_esdb@node2,ex_esdb@node3,ex_esdb@node4"
    # healthcheck:
    #   test: ["CMD-SHELL", "./check-ex-esdb.sh"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 30s
    # depends_on:
    #   ex-esdb0:
    #     condition: service_healthy

  ex-esdb2:
    image: local/ex-esdb
    build:
      context: ../system
    hostname: node2
    container_name: ex-esdb2
    volumes:
      - esdb2-data:/data
    networks:
      - esdb-net
    environment:
      EX_ESDB_STORE_ID: "reg_gh"
      EX_ESDB_COOKIE: "reg_gh_clique1"
      EX_ESDB_SEED_NODES: "ex_esdb@node0,ex_esdb@node1,ex_esdb@node3,ex_esdb@node4"
    # healthcheck:
    #   test: ["CMD-SHELL", "./check-ex-esdb.sh"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 30s
    # depends_on:
    #   ex-esdb1:
    #     condition: service_healthy

  ex-esdb3:
    image: local/ex-esdb
    build:
      context: ../system
    hostname: node3
    container_name: ex-esdb3
    volumes:
      - esdb3-data:/data
    networks:
      - esdb-net
    environment:
      EX_ESDB_STORE_ID: "reg_gh"
      EX_ESDB_COOKIE: "reg_gh_clique1"
      EX_ESDB_SEED_NODES: "ex_esdb@node0,ex_esdb@node1,ex_esdb@node2,ex_esdb@node4"
    # healthcheck:
    #   test: ["CMD-SHELL", "./check-ex-esdb.sh"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 30s
    # depends_on:
    #   ex-esdb2:
    #     condition: service_healthy

  ex-esdb4:
    image: local/ex-esdb
    build:
      context: ../system
    hostname: node4
    container_name: ex-esdb4
    volumes:
      - esdb4-data:/data
    networks:
      - esdb-net
    environment:
      EX_ESDB_STORE_ID: "reg_gh"
      EX_ESDB_COOKIE: "reg_gh_clique1"
      EX_ESDB_SEED_NODES: "ex_esdb@node0,ex_esdb@node1,ex_esdb@node2,ex_esdb@node3"
    # healthcheck:
    #   test: ["CMD-SHELL", "./check-ex-esdb.sh"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 30s
    # depends_on:
    #   ex-esdb3:
    #     condition: service_healthy
