networks:
  ex-esdb-net:
    name: ex-esdb-net
    driver: bridge

volumes:
  ex-esdb0-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume/ex-esdb/data0

  ex-esdb1-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume/ex-esdb/data1

  ex-esdb2-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume/ex-esdb/data2

  ex-esdb3-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume/ex-esdb/data3

  ex-esdb4-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume/ex-esdb/data4

services:
  ex-esdb0:
    image: local/ex-esdb
    build:
      context: ../system
    hostname: node0
    container_name: ex-esdb0
    networks:
      - ex-esdb-net
    volumes:
      - ex-esdb0-data:/data
    stop_grace_period: 10s
    environment:
      EX_ESDB_STORE_ID: "reg_gh"
      EX_ESDB_COOKIE: "reg_greenhouse_cookie"
      EX_ESDB_SEED_NODES: "ex_esdb@node1,ex_esdb@node2,ex_esdb@node3,ex_esdb@node4"

  ex-esdb1:
    image: local/ex-esdb
    build:
      context: ../system
    hostname: node1
    container_name: ex-esdb1
    networks:
      - ex-esdb-net
    volumes:
      - ex-esdb1-data:/data
    environment:
      EX_ESDB_STORE_ID: "reg_gh"
      EX_ESDB_COOKIE: "reg_greenhouse_cookie"
      EX_ESDB_SEED_NODES: "ex_esdb@node0,ex_esdb@node2,ex_esdb@node3,ex_esdb@node4"
    stop_grace_period: 10s
    depends_on:
      ex-esdb0:
        condition: service_healthy

  ex-esdb2:
    image: local/ex-esdb
    build:
      context: ../system
    hostname: node2
    container_name: ex-esdb2
    networks:
      - ex-esdb-net
    volumes:
      - ex-esdb2-data:/data
    environment:
      EX_ESDB_STORE_ID: "reg_gh"
      EX_ESDB_COOKIE: "reg_greenhouse_cookie"
      EX_ESDB_SEED_NODES: "ex_esdb@node0,ex_esdb@node1,ex_esdb@node3,ex_esdb@node4"
    depends_on:
      ex-esdb0:
        condition: service_healthy
    stop_grace_period: 10s

  ex-esdb3:
    image: local/ex-esdb
    build:
      context: ../system
    hostname: node3
    container_name: ex-esdb3
    networks:
      - ex-esdb-net
    volumes:
      - ex-esdb3-data:/data
    environment:
      EX_ESDB_STORE_ID: "reg_gh"
      EX_ESDB_COOKIE: "reg_greenhouse_cookie"
      EX_ESDB_SEED_NODES: "ex_esdb@node0,ex_esdb@node1,ex_esdb@node2,ex_esdb@node4"
    depends_on:
      ex-esdb0:
        condition: service_healthy
    stop_grace_period: 10s

  ex-esdb4:
    image: local/ex-esdb
    build:
      context: ../system
    hostname: node4
    container_name: ex-esdb4
    networks:
      - ex-esdb-net
    volumes:
      - ex-esdb4-data:/data
    environment:
      EX_ESDB_STORE_ID: "reg_gh"
      EX_ESDB_COOKIE: "reg_greenhouse_cookie"
      EX_ESDB_SEED_NODES: "ex_esdb@node0,ex_esdb@node1,ex_esdb@node2,ex_esdb@node3"
    stop_grace_period: 10s
    depends_on:
      ex-esdb0:
        condition: service_healthy
