networks:
  scarab-net:
    name: scarab-net
    driver: bridge

volumes:
  scarab0-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume/scarab/data0

  scarab1-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume/scarab/data1

  scarab2-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume/scarab/data2

services:
  scarab0:
    image: local/scarab_es
    build:
      context: ../system
    hostname: scarab0
    container_name: scarab0
    networks:
      - scarab-net
    volumes:
      - scarab0-data:/data
    environment:
      SCARAB_STORE: "reg_greenhouse"
      SCARAB_COOKIE: "reg_greenhouse_cookie"
      SCARAB_SEEDS: "scarab_es@scarab0, scarab_es@scarab1, scarab_es@scarab2"
  #    healthcheck:
  #    test: ["CMD", "epmd", -names | grep scarab_es@scarab0]

  scarab1:
    image: local/scarab-es
    build:
      context: ../system
    hostname: scarab1
    container_name: scarab1
    networks:
      - scarab-net
    volumes:
      - scarab1-data:/data
    environment:
      SCARAB_STORE: "reg_greenhouse"
      SCARAB_COOKIE: "reg_greenhouse_cookie"
      SCARAB_SEEDS: "scarab_es@scarab0"
    depends_on:
      - scarab0

  scarab2:
    image: local/scarab-es
    build:
      context: ../system
    hostname: scarab2
    container_name: scarab2
    networks:
      - scarab-net
    volumes:
      - scarab2-data:/data
    environment:
      SCARAB_STORE: "reg_greenhouse"
      SCARAB_COOKIE: "reg_greenhouse_cookie"
      SCARAB_SEEDS: "scarab_es@scarab0"
    depends_on:
      - scarab0
